// Dummy-Daten für Benachrichtigungen
export const dummyNotifications: UserNotificationProps[] = [
  {
      id: "1",
      category: "Meeting",
      message: "Monatliches Team-Meeting",
      date: "2024-06-01T09:00:00",
      status: "unread",
      type: "Notification",
  },
  {
      id: "2",
      category: "Interview",
      message: "Interview mit John Doe",
      date: "2024-06-05T14:00:00",
      status: "unread",
      type: "Notification",
  },
  {
      id: "3",
      category: "Reminder",
      message: "Monatsbericht einreichen",
      date: "2024-06-10T12:00:00",
      status: "unread",
      type: "Reminder",
  },
  {
      id: "4",
      category: "Other",
      message: "Überprüfen Sie den Wartungsstatus des Servers",
      date: "2024-06-15T10:30:00",
      status: "unread",
      type: "Notification",
  },
  {
      id: "5",
      category: "Discussion",
      message: "Team-Diskussion über Projektupdates",
      date: "2024-06-20T15:00:00",
      status: "unread",
      type: "Notification",
  },
  {
      id: "6",
      category: "Other",
      message: "Schulung für neue Mitarbeiter",
      date: "2024-06-25T11:00:00",
      status: "unread",
      type: "Notification",
  },
];
